stages:
  - build
  - test

default:
  image: rust:1.82-slim
  cache:
    key: rust-build-cache
    paths:
      - .cargo/
      - .rustup/
      - target/

build:
  stage: build
  script:
    - cd gng
    - cargo build --release

test:
  stage: test
  script:
    - cd gng
    - cargo test --all --release
  dependencies:
    - build