[package]
name = "neurogas"
version = "0.0.1"
edition = "2021"
readme = "Readme.md"
repository = "https://gitlab.com/br34ch/project_flood/rust_gng"

[dependencies]
csv = "1.3.1"
fast-math = "0.1.1"
json = "0.12.4"
num = "0.4.3"
num-traits = "0.2.19"
rand = "0.9.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
backtrace="0.3"

[lib]
name = "neurogas"
crate-type = ["lib"]

[[bin]]
name = "debug_runner"
path = "src/bin/debug_runner.rs"