name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v22

    - name: Run tests in nix-shell
      run: nix-shell --run "cd gng_py && cargo test"
